[book]
title = "Atlaspad"
authors = ["Atlaspad Developer Team"]
description = "An introduction to the Atlaspad Ecosystem, showcasing solutions offered by Atlaspad."
language = "en"
text-direction = "ltr"

[build]
build-dir = "src"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = ["style.css"]
git-repository-url = "https://github.com/atlaspad/docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/atlaspad/docs/issues/new"

[output.html.search]
limit-results = 15
